// alert
export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'
// loader
export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'
// toast
export const SHOW_TOAST = 'SHOW_TOAST'
export const HIDE_TOAST = 'HIDE_TOAST'

export const ADD_TO_CART = 'ADD_TO_CART'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const GET_SCORE_INDEX_DATA = 'GET_SCORE_INDEX_DATA'
// login
export const GET_LOGIN_INFO = 'GET_LOGIN_INFO'
// invite
export const UPDATE_INVITE_DATA = 'UPDATE_INVITE_DATA'
export const GET_SCORE_DETAIL_DATA = 'GET_SCORE_DETAIL_DATA'
export const CHANGE_SCORE_DETAIL_BTN_TYPE = 'CHANGE_SCORE_DETAIL_BTN_TYPE'
export const GET_SCORE_RECORD_DATA = 'GET_SCORE_RECORD_DATA'

// check01
export const CHECKSIGN_SUCCESS = 'CHECKSIGN_SUCCESS'
export const CHECKSIGN_FAILE = 'CHECKSIGN_FAILE'
export const CHECKONSIGN_SUCCESS = 'CHECKONSIGN_SUCCESS'
export const CHECKONSIGN_FAILE = 'CHECKONSIGN_FAILE'

// score foun
export const UPDATE_SCORE_FOUN_DATA = 'UPDATE_SCORE_FOUN_DATA'
export const UPDATE_SCORE_FOUN_STATUS = 'UPDATE_SCORE_FOUN_STATUS'
export const SCORE_CHANGE_CODE = 'SCORE_CHANGE_CODE'
export const REST_SCORE_CODE = 'REST_SCORE_CODE'
// my score
export const UPDATE_MY_SCORE = 'UPDATE_MY_SCORE'
export const UPDATE_MY_SCORE_STATUS = 'UPDATE_MY_SCORE_STATUS'
// investment
export const GET_INVESTMENT_DETAIL_DATA = 'GET_INVESTMENT_DETAIL_DATA'
// asset detail
export const GET_INVEST_DETAIL_DATA = 'GET_INVEST_DETAIL_DATA' //投资详情
export const GET_TRANSLATE_DETAIL_DATA = 'GET_TRANSLATE_DETAIL_DATA' //变现详情

// title refresher
export const ASSIGN_TITLE_REFRESHER = 'ASSIGN_TITLE_REFRESHER'
export const ASSIGN_TITLE_REFRESHER_SRC = 'ASSIGN_TITLE_REFRESHER_SRC'
